/**
 * The package-to-stdlib mapping table.
 *
 * This is deliberately data, not code: a judge (or a user who disagrees with a
 * verdict) should be able to read the whole ruleset top to bottom without
 * following a single function call.
 *
 * `weekly` figures are static, sourced from the Zero Dependency cheat-sheet
 * (verified 27 August 2026) and from npm registry download counts read by hand on
 * 31 August 2026. shed never makes a network request, so these numbers age; they
 * are indicative of scale, not live telemetry.
 *
 * `confidence` drives the verdict:
 *   'exact'   - a drop-in replacement; safe to recommend and sometimes to codemod
 *   'partial' - the stdlib covers the common path, but named caveats can block it
 */

/**
 * @typedef {object} Entry
 * @property {string} pkg           npm package name
 * @property {number|null} weekly    approximate weekly downloads, or null if unknown
 * @property {string} api            the standard-library API that replaces it
 * @property {string} since          minimum Node version where `api` is usable
 * @property {'exact'|'partial'} confidence
 * @property {string} rationale      one line on what the swap actually costs
 * @property {string[]} [caveats]    usage that defeats the swap; probed in source
 * @property {string} [docs]         nodejs.org anchor, printed by `shed why`
 */

/** @type {Entry[]} */
export const ENTRIES = [
  {
    pkg: 'chalk',
    weekly: 319_800_000,
    api: 'util.styleText()',
    since: '20.12.0',
    confidence: 'partial',
    rationale: 'styleText covers named colours and modifiers; the chainable API and level detection are yours to write.',
    caveats: ['.level', '.hex(', '.rgb(', '.bgHex(', '.ansi256(', 'supportsColor'],
    docs: 'util.html#utilstyletextformat-text-options',
  },
  {
    pkg: 'colors',
    weekly: 2_000_000,
    api: 'util.styleText()',
    since: '20.12.0',
    confidence: 'partial',
    rationale: 'Same substitution as chalk, minus the String.prototype patching that made colors infamous.',
    caveats: ['.zalgo', '.rainbow', 'setTheme'],
  },
  {
    pkg: 'picocolors',
    weekly: 180_000_000,
    api: 'util.styleText()',
    since: '20.12.0',
    confidence: 'exact',
    rationale: 'picocolors is already a thin wrapper over escape codes; styleText is the same idea in the runtime.',
  },
  {
    pkg: 'strip-ansi',
    weekly: 190_000_000,
    api: 'util.stripVTControlCharacters()',
    since: '18.0.0',
    confidence: 'exact',
    rationale: 'Identical intent, and the stdlib version also strips non-colour VT sequences.',
  },
  {
    pkg: 'ansi-styles',
    weekly: 200_000_000,
    api: 'util.styleText()',
    since: '20.12.0',
    confidence: 'partial',
    rationale: 'styleText applies styles; it does not expose the raw open/close code pairs ansi-styles is used for.',
    caveats: ['.open', '.close'],
  },
  {
    pkg: 'readable-stream',
    weekly: 185_600_000,
    api: 'node:stream + node:stream/promises',
    since: '18.0.0',
    confidence: 'exact',
    rationale: 'readable-stream exists to backport core streams to old Node; on a supported Node it is the same code.',
  },
  {
    pkg: 'form-data',
    weekly: 100_900_000,
    api: 'global FormData with fetch',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'The web FormData covers multipart bodies for fetch; the getHeaders()/pipe() surface has no equivalent.',
    caveats: ['getHeaders', 'getLengthSync', '.pipe('],
  },
  {
    pkg: 'minimist',
    weekly: 80_500_000,
    api: 'util.parseArgs()',
    since: '18.3.0',
    confidence: 'partial',
    rationale: 'parseArgs is string-and-boolean only by design; subcommands, negation and coercion are ~80 lines you write.',
    // Distinctive spellings only: a bare '--' would match any comment.
    caveats: ["'--':", "['--']", '"--":'],
    docs: 'util.html#utilparseargsconfig',
  },
  {
    pkg: 'yargs-parser',
    weekly: 90_000_000,
    api: 'util.parseArgs()',
    since: '18.3.0',
    confidence: 'partial',
    rationale: 'Same trade as minimist, with more coercion behaviour to reimplement.',
  },
  {
    pkg: 'commander',
    weekly: 130_000_000,
    api: 'util.parseArgs() plus a dispatch table',
    since: '18.3.0',
    confidence: 'partial',
    rationale: 'Tokenising is free; generated help and subcommand routing are the part you keep.',
  },
  {
    pkg: 'node-fetch',
    weekly: 55_000_000,
    api: 'global fetch()',
    since: '18.0.0',
    confidence: 'exact',
    rationale: 'Node ships Undici as the global fetch; node-fetch is the polyfill it made redundant.',
  },
  {
    pkg: 'axios',
    weekly: 55_000_000,
    api: 'global fetch()',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'fetch covers requests and responses; interceptors, automatic JSON and progress events are not in the box.',
    caveats: [
      'interceptors', 'axios.create', 'onUploadProgress', 'onDownloadProgress',
      'timeout:', 'validateStatus', 'maxRedirects', 'responseType', 'withCredentials',
    ],
  },
  {
    pkg: 'uuid',
    weekly: 130_000_000,
    api: 'crypto.randomUUID()',
    since: '14.17.0',
    confidence: 'partial',
    rationale: 'randomUUID is v4 only; v1/v5/v7 and the parse/stringify helpers have no stdlib equivalent.',
    // Anchored to a call or a member access: bare 'parse' would fire on JSON.parse.
    caveats: ['v1(', 'v3(', 'v5(', 'v6(', 'v7(', 'uuidv1', 'uuidv7', 'uuid.parse', 'uuid.stringify', 'uuid.validate'],
  },
  {
    pkg: 'nanoid',
    weekly: 40_000_000,
    api: 'crypto.randomUUID() or crypto.randomBytes()',
    since: '14.17.0',
    confidence: 'partial',
    rationale: 'A URL-safe id is randomBytes plus base64url; nanoid keeps its edge only on custom alphabets and length.',
    caveats: ['customAlphabet', 'customRandom'],
  },
  {
    pkg: 'glob',
    weekly: 180_000_000,
    api: 'fs.glob() / fs.globSync()',
    since: '22.0.0',
    confidence: 'partial',
    rationale: 'fs.glob covers the common patterns; the ignore/cwd/dot option surface is smaller.',
    caveats: ['nodir', 'absolute', 'dot:', 'ignore:', 'cwd:', 'follow:'],
    docs: 'fs.html#fsglobpattern-options-callback',
  },
  {
    pkg: 'fast-glob',
    weekly: 90_000_000,
    api: 'fs.globSync()',
    since: '22.0.0',
    confidence: 'partial',
    rationale: 'Same substitution as glob, with a real performance regression on very large trees - measure before you swap.',
    caveats: ['onlyFiles', 'onlyDirectories', 'absolute', 'ignore:', 'objectMode', 'stats:', 'deep:'],
  },
  {
    pkg: 'rimraf',
    weekly: 70_000_000,
    api: 'fs.rm(path, { recursive: true, force: true })',
    since: '14.14.0',
    confidence: 'exact',
    rationale: 'Core absorbed recursive delete outright; rimraf now mostly wraps it.',
  },
  {
    pkg: 'mkdirp',
    weekly: 40_000_000,
    api: 'fs.mkdir(path, { recursive: true })',
    since: '10.12.0',
    confidence: 'exact',
    rationale: 'One option flag replaced the whole package.',
  },
  {
    pkg: 'dotenv',
    weekly: 45_000_000,
    api: 'process.loadEnvFile() or node --env-file',
    since: '20.6.0',
    confidence: 'partial',
    rationale: 'Core loads a .env; variable expansion and multi-file precedence are not covered.',
    caveats: ['dotenv.parse', 'dotenv.populate', 'dotenv-expand'],
  },
  {
    pkg: 'debug',
    weekly: 250_000_000,
    api: 'util.debuglog()',
    since: '0.11.0',
    confidence: 'partial',
    rationale: 'debuglog is namespaced, lazily evaluated and driven by NODE_DEBUG; the wildcard grammar is narrower.',
  },
  {
    pkg: 'nodemon',
    weekly: 7_800_000,
    api: 'node --watch',
    since: '18.11.0',
    confidence: 'partial',
    rationale: 'Core restarts on change; ignore globs and per-extension rules are still nodemon-only.',
  },
  {
    pkg: 'ws',
    weekly: 90_000_000,
    api: 'global WebSocket',
    since: '22.0.0',
    confidence: 'partial',
    rationale: 'The global is a client. There is still no WebSocket *server* in Node core.',
    caveats: ['WebSocketServer', 'Server('],
  },
  {
    pkg: 'better-sqlite3',
    weekly: 2_000_000,
    api: 'node:sqlite',
    since: '24.15.0',
    confidence: 'partial',
    rationale: 'node:sqlite reached Release Candidate (Stability 1.2) with no flag; the API is narrower but real.',
  },
  {
    pkg: 'jest',
    weekly: 30_000_000,
    api: 'node:test + node:assert',
    since: '20.0.0',
    confidence: 'partial',
    rationale: 'Runner, assertions, coverage and mocks are all in core; snapshot testing and module mocking are not at parity.',
    caveats: ['toMatchSnapshot', 'jest.mock', 'jest.spyOn'],
  },
  {
    pkg: 'mocha',
    weekly: 8_000_000,
    api: 'node:test',
    since: '20.0.0',
    confidence: 'partial',
    rationale: 'describe/it map onto test/t.test directly, but hooks, .only/.skip and the reporter flags are not at parity.',
    caveats: ['this.timeout(', 'this.retries(', '.only(', 'before(', 'after(', 'beforeEach(', 'afterEach('],
  },
  {
    pkg: 'chai',
    weekly: 9_000_000,
    api: 'node:assert/strict',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'Core assertions cover equality and throws; the fluent BDD chain is a style you give up.',
    caveats: ['expect(', 'should', '.to.', 'chai.use(', 'deep.equal'],
  },
  {
    pkg: 'cross-env',
    weekly: 15_000_000,
    api: 'node --env-file or npm lifecycle env',
    since: '20.6.0',
    confidence: 'partial',
    rationale: 'Only needed for Windows shell differences; a .env file sidesteps the shell entirely.',
  },
  {
    pkg: 'once',
    weekly: 60_000_000,
    api: 'events.once() or a closure',
    since: '11.13.0',
    confidence: 'exact',
    rationale: 'Three lines, or one core import.',
  },
  {
    pkg: 'p-limit',
    weekly: 90_000_000,
    api: 'a Promise.race pool (~20 lines)',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'There is no stdlib API for this at all - the replacement is roughly twenty lines of Promise.race you write and own.',
  },
  {
    pkg: 'lodash.get',
    weekly: 12_000_000,
    api: 'optional chaining (?.)',
    since: '14.0.0',
    confidence: 'partial',
    rationale: 'Optional chaining replaces it for literal paths; a path computed at runtime needs a reduce over split(\'.\').',
    caveats: ['get(obj,', 'get(data,', '.get(', 'lodash.get('],
  },
  {
    pkg: 'deepmerge',
    weekly: 25_000_000,
    api: 'structuredClone() plus a merge you write',
    since: '17.0.0',
    confidence: 'partial',
    rationale: 'Cloning is stdlib; merge policy is application-specific and always was.',
  },
  {
    pkg: 'node-forge',
    weekly: 20_000_000,
    api: 'node:crypto',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'Core covers hashing, HMAC, AES-GCM, key derivation and X.509 verification. Do not swap crypto casually.',
    caveats: ['forge.pki.createCertificate', 'forge.asn1'],
  },
  {
    pkg: 'express',
    weekly: 35_000_000,
    api: 'node:http',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'node:http serves requests; routing, middleware and body parsing are the parts express actually sells.',
    // Routing is the thing express is actually for, so any route registration
    // blocks the swap. Without app.get/post/res.json here, an ordinary Express
    // app came back "removable" directly above a rationale saying routing is
    // what express sells.
    caveats: [
      'app.use(', 'app.get(', 'app.post(', 'app.put(', 'app.patch(', 'app.delete(',
      'app.listen(', 'express.Router', 'express.static', 'req.body', 'req.params',
      'req.query', 'res.json(', 'res.render', 'res.redirect(', 'res.sendFile(',
    ],
  },
  {
    pkg: 'body-parser',
    weekly: 30_000_000,
    api: 'the request stream plus JSON.parse',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'Reading a JSON body is a for-await over the request; urlencoded and multipart are not.',
    caveats: ['urlencoded', 'multipart', '.raw('],
  },
  {
    pkg: 'cors',
    weekly: 20_000_000,
    api: 'Access-Control-* response headers',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'A permissive CORS policy is four setHeader calls; per-origin allow-lists and preflight caching are yours.',
    caveats: ['credentials:', 'preflightContinue', 'optionsSuccessStatus'],
  },
  {
    pkg: 'helmet',
    weekly: 4_000_000,
    api: 'response headers set by hand',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'Every header helmet sets is one setHeader call, but you take on tracking the defaults it maintains.',
    caveats: ['contentSecurityPolicy', 'hsts'],
  },
  {
    pkg: 'cookie-parser',
    weekly: 8_000_000,
    api: 'splitting the Cookie header',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'Parsing is a split and a decodeURIComponent; signed cookies need an HMAC you write over node:crypto.',
    caveats: ['signedCookies'],
  },
  {
    pkg: 'jsonwebtoken',
    weekly: 18_000_000,
    api: 'crypto.createHmac + base64url',
    since: '15.7.0',
    confidence: 'partial',
    rationale: 'HS256 sign and verify is about thirty lines over node:crypto, with timingSafeEqual for the comparison.',
    caveats: ['jwksClient', 'JwksClient', 'jwks-rsa'],
  },
  {
    pkg: 'bcrypt',
    weekly: 2_500_000,
    api: 'crypto.scrypt()',
    since: '10.5.0',
    confidence: 'partial',
    rationale: 'scrypt is a memory-hard KDF in core, but it is a different algorithm: every existing hash must be re-derived on next login, so this is a migration, not a swap.',
    caveats: ['compare(', 'compareSync', 'hashSync', '.hash('],
  },
  {
    pkg: 'bcryptjs',
    weekly: 3_000_000,
    api: 'crypto.scrypt()',
    since: '10.5.0',
    confidence: 'partial',
    rationale: 'Same migration as bcrypt - existing hashes stop verifying - though the pure-JS implementation being replaced is also the slower one.',
    caveats: ['compare(', 'compareSync', 'hashSync', '.hash('],
  },
  {
    pkg: 'qs',
    weekly: 90_000_000,
    api: 'URLSearchParams',
    since: '10.0.0',
    confidence: 'partial',
    rationale: 'URLSearchParams covers flat query strings; qs exists for the nested bracket syntax it does not parse.',
    caveats: ['allowDots', 'arrayFormat', 'depth:', '[]='],
  },
  {
    pkg: 'query-string',
    weekly: 15_000_000,
    api: 'URLSearchParams',
    since: '10.0.0',
    confidence: 'partial',
    rationale: 'Same substitution as qs, with the same nested-object caveat.',
    caveats: ['arrayFormat', 'parseNumbers'],
  },
  {
    pkg: 'fs-extra',
    weekly: 90_000_000,
    api: 'node:fs/promises with fs.cp and fs.rm',
    since: '22.3.0',
    confidence: 'partial',
    rationale: 'Core absorbed recursive copy, remove and mkdir; the JSON helpers are a readFile and a JSON.parse.',
    caveats: ['readJson', 'writeJson', 'outputFile', 'ensureSymlink'],
  },
  {
    pkg: 'globby',
    weekly: 20_000_000,
    api: 'fs.globSync()',
    since: '22.0.0',
    confidence: 'partial',
    rationale: 'Core glob covers the patterns; globby\'s gitignore awareness is about sixty lines you write once.',
    caveats: ['gitignore'],
  },
  {
    pkg: 'chokidar',
    weekly: 60_000_000,
    api: 'fs.watch()',
    since: '20.0.0',
    confidence: 'partial',
    rationale: 'Recursive fs.watch works on every major platform since 20; debouncing and rename coalescing are still yours.',
    caveats: ['awaitWriteFinish', 'usePolling', 'ignoreInitial'],
  },
  {
    pkg: 'execa',
    weekly: 90_000_000,
    api: 'child_process.execFile with promisify',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'Core spawns processes; the ergonomics execa adds - shell-free templates, better errors - are the value.',
    caveats: ['execaCommand', '.pipeStdout', 'reject: false'],
  },
  {
    pkg: 'object-assign',
    weekly: 50_000_000,
    api: 'Object.assign()',
    since: '4.0.0',
    confidence: 'exact',
    rationale: 'The language grew the function this package existed to polyfill, a decade ago.',
  },
  {
    pkg: 'left-pad',
    weekly: 300_000,
    api: 'String.prototype.padStart()',
    since: '8.0.0',
    confidence: 'exact',
    rationale: 'The original sin, retired by one line of ECMAScript.',
  },
  {
    pkg: 'clsx',
    weekly: 30_000_000,
    api: 'a filter and a join',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'String and object arguments are a filter and a join; the nested-array form clsx also accepts needs a small recursive helper, nearer a dozen lines than five.',
    caveats: ['clsx({', 'clsx([', 'ClassValue'],
  },
  {
    pkg: 'classnames',
    weekly: 15_000_000,
    api: 'a filter and a join',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'Identical to clsx, including the nested-array form that makes the one-liner version wrong.',
    caveats: ['classNames({', 'classNames(['],
  },
  {
    pkg: 'dayjs',
    weekly: 25_000_000,
    api: 'Intl.DateTimeFormat and Date',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'Intl formats and localises better than any package; date arithmetic and parsing are where you still write code.',
    // .format() with a token string is dayjs's most-used call and Intl cannot
    // do token formats at all, so omitting it made the common case "removable".
    caveats: ['.format(', '.add(', '.subtract(', '.diff(', '.fromNow(', '.startOf(', '.endOf(', 'customParseFormat'],
  },
  {
    pkg: 'moment',
    weekly: 12_000_000,
    api: 'Intl.DateTimeFormat and Date',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'Moment is in maintenance mode and says so itself; Intl covers formatting, arithmetic does not come free.',
    caveats: ['.format(', '.add(', '.subtract(', '.diff(', '.fromNow(', '.startOf(', '.endOf(', '.tz('],
  },
  {
    pkg: 'crypto-js',
    weekly: 6_000_000,
    api: 'node:crypto',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'Core does SHA, HMAC and AES natively and faster; the browser-oriented WordArray API has no equivalent.',
    caveats: ['WordArray', 'enc.Hex', 'enc.Base64'],
  },
  {
    pkg: 'md5',
    weekly: 3_000_000,
    api: "crypto.createHash('md5')",
    since: '0.1.0',
    confidence: 'exact',
    rationale: 'One core call, and faster than the JavaScript implementation.',
  },
  {
    pkg: 'abort-controller',
    weekly: 30_000_000,
    api: 'global AbortController',
    since: '15.0.0',
    confidence: 'exact',
    rationale: 'A polyfill for something that has been global for five major versions.',
  },
  {
    pkg: 'pify',
    weekly: 20_000_000,
    api: 'util.promisify()',
    since: '8.0.0',
    confidence: 'exact',
    rationale: 'Core has promisified callbacks since Node 8, and node:fs/promises removes most of the need entirely.',
  },
  {
    pkg: 'concat-stream',
    weekly: 12_000_000,
    api: 'stream/consumers',
    since: '16.7.0',
    confidence: 'exact',
    rationale: 'consumers.buffer / .text / .json collect a stream in one await.',
  },
  {
    pkg: 'yargs',
    weekly: 80_000_000,
    api: 'util.parseArgs()',
    since: '18.3.0',
    confidence: 'partial',
    rationale: 'Tokenising is free; generated help, commands and validation are the parts you keep writing.',
    caveats: ['.command(', '.demandOption', '.middleware('],
  },
  {
    pkg: 'vitest',
    weekly: 12_000_000,
    api: 'node:test',
    since: '20.0.0',
    confidence: 'partial',
    rationale: 'Core has the runner, assertions, coverage and watch mode; module mocking and snapshots are not at parity.',
    caveats: ['vi.mock', 'vi.spyOn', 'toMatchSnapshot', 'vi.fn('],
  },
  {
    pkg: 'inquirer',
    weekly: 25_000_000,
    api: 'node:readline/promises',
    since: '17.0.0',
    confidence: 'partial',
    rationale: 'Questions and answers are one await; arrow-key list pickers mean driving raw mode yourself.',
    caveats: ['type: \'list\'', 'type: \'checkbox\'', 'inquirer.prompt'],
  },
  {
    pkg: 'ora',
    weekly: 20_000_000,
    api: 'raw ANSI plus setInterval',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'A spinner is a frame array, a timer and \\r; the TTY and CI detection is the part worth copying.',
  },
  {
    pkg: 'sqlite3',
    weekly: 1_500_000,
    api: 'node:sqlite',
    since: '24.15.0',
    confidence: 'partial',
    rationale: 'node:sqlite is a Release Candidate with no flag; the API is narrower and synchronous by default.',
  },
  {
    pkg: 'lodash',
    weekly: 60_000_000,
    api: 'native array, object and language features',
    since: '21.0.0',
    confidence: 'partial',
    rationale: 'map/filter/find/flat/at/groupBy are all native now; debounce, cloneDeep and the lazy chain are what is left.',
    caveats: ['.debounce(', '.throttle(', '.cloneDeep(', '.merge(', '_.chain(', '.memoize('],
  },
  {
    pkg: 'core-js',
    weekly: 45_000_000,
    api: 'the language itself',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'A polyfill set for features Node has shipped for years; it survives in build output long after the targets that needed it.',
  },
  {
    pkg: 'deep-equal',
    weekly: 15_000_000,
    api: 'util.isDeepStrictEqual()',
    since: '9.0.0',
    confidence: 'partial',
    rationale: "Core handles cycles and typed arrays correctly, but compares strictly; deep-equal's default is loose (==), so a swap changes results unless you already pass { strict: true }.",
    caveats: ['strict: false', 'deepEqual('],
  },
  {
    pkg: 'fast-deep-equal',
    weekly: 60_000_000,
    api: 'util.isDeepStrictEqual()',
    since: '9.0.0',
    confidence: 'exact',
    rationale: 'Same substitution as deep-equal; the package is faster on hot paths, so measure before swapping in one.',
  },
  {
    pkg: 'lodash.isequal',
    weekly: 12_000_000,
    api: 'util.isDeepStrictEqual()',
    since: '9.0.0',
    confidence: 'exact',
    rationale: 'One core call replaces the whole package.',
  },
  {
    pkg: 'url-parse',
    weekly: 12_000_000,
    api: 'the global URL',
    since: '10.0.0',
    confidence: 'partial',
    rationale: 'URL is the WHATWG parser and has been global for years; url-parse is laxer about malformed input.',
    caveats: ['slashesDenoteHost'],
  },
  {
    pkg: 'whatwg-url',
    weekly: 25_000_000,
    api: 'the global URL',
    since: '10.0.0',
    confidence: 'exact',
    rationale: 'This is the implementation Node already exposes globally.',
  },
  {
    pkg: 'base64-js',
    weekly: 50_000_000,
    api: "Buffer.from(s, 'base64')",
    since: '4.5.0',
    confidence: 'partial',
    rationale: 'Buffer does base64 and base64url natively; the package exists for browsers, where atob and Uint8Array do the same job.',
  },
  {
    pkg: 'safe-buffer',
    weekly: 60_000_000,
    api: 'Buffer.from / Buffer.alloc',
    since: '4.5.0',
    confidence: 'exact',
    rationale: 'A shim for the pre-4.5 Buffer constructor. Nothing supported still needs it.',
  },
  {
    pkg: 'text-encoding',
    weekly: 1_000_000,
    api: 'the global TextEncoder / TextDecoder',
    since: '11.0.0',
    confidence: 'exact',
    rationale: 'Global since Node 11.',
  },
  {
    pkg: 'iconv-lite',
    weekly: 40_000_000,
    api: 'TextDecoder',
    since: '11.0.0',
    confidence: 'partial',
    rationale: 'TextDecoder covers utf-8, latin1, utf-16 and the common single-byte pages; the long tail of legacy encodings is why iconv-lite exists.',
    caveats: ['encodeTo', 'iconv.encode', 'win1251', 'shift_jis', 'gbk', 'big5'],
  },
  {
    pkg: 'array-flatten',
    weekly: 30_000_000,
    api: 'Array.prototype.flat()',
    since: '11.0.0',
    confidence: 'exact',
    rationale: 'One method, native since Node 11.',
  },
  {
    pkg: 'es6-promise',
    weekly: 8_000_000,
    api: 'the native Promise',
    since: '4.0.0',
    confidence: 'exact',
    rationale: 'A polyfill for something the language has had for a decade.',
  },
  {
    pkg: 'bluebird',
    weekly: 12_000_000,
    api: 'native promises with async/await',
    since: '8.0.0',
    confidence: 'partial',
    rationale: 'Native promises cover the common path; Promise.map, .each and cancellation are Bluebird-only.',
    caveats: ['Promise.map', 'Promise.each', 'Promise.props', '.cancel(', 'promisifyAll'],
  },
  {
    pkg: 'async',
    weekly: 45_000_000,
    api: 'async/await with Promise.all',
    since: '8.0.0',
    confidence: 'partial',
    rationale: 'Sequential and parallel flows are language features now; the queue and cargo abstractions are not.',
    caveats: ['async.queue', 'async.cargo', 'async.auto', 'async.retry'],
  },
  {
    pkg: 'eventemitter3',
    weekly: 30_000_000,
    api: 'node:events',
    since: '0.10.0',
    confidence: 'partial',
    rationale: 'Core EventEmitter is the same API; eventemitter3 exists to be faster and to run in browsers.',
  },
  {
    pkg: 'request',
    weekly: 8_000_000,
    api: 'global fetch()',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'Deprecated since 2020 and still installed millions of times a week; fetch covers most of what it was used for.',
    caveats: ['request.jar', 'followAllRedirects', 'forever:'],
  },
  {
    pkg: 'superagent',
    weekly: 8_000_000,
    api: 'global fetch()',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'fetch covers requests and responses; the plugin chain and retry logic are yours to write.',
    caveats: ['.retry(', '.use(', '.attach('],
  },
  {
    pkg: 'got',
    weekly: 25_000_000,
    api: 'global fetch()',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'fetch is the same transport; got keeps its edge on retries, hooks and streaming ergonomics.',
    caveats: ['retry:', 'hooks:', '.stream', 'pagination'],
  },
  {
    pkg: 'jwt-decode',
    weekly: 6_000_000,
    api: "Buffer.from(part, 'base64url') plus JSON.parse",
    since: '15.7.0',
    confidence: 'partial',
    rationale: 'Decoding a JWT payload is three lines - and this package only decodes, it never verifies, which is the part people forget.',
  },
  {
    pkg: 'pretty-bytes',
    weekly: 8_000_000,
    api: 'Intl.NumberFormat with notation: "compact"',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'Intl formats and localises the number; the unit ladder is about ten lines.',
  },
  {
    pkg: 'filesize',
    weekly: 3_000_000,
    api: 'Intl.NumberFormat',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'Same substitution as pretty-bytes, with the same ten-line unit ladder.',
  },
  {
    pkg: 'numeral',
    weekly: 1_500_000,
    api: 'Intl.NumberFormat',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'Intl handles currency, percent, compact notation and locale rules better than any package, and is unmaintained-proof.',
    caveats: ['numeral.register', '.unformat('],
  },
  {
    pkg: 'debounce',
    weekly: 6_000_000,
    api: 'setTimeout and a closure',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'Five lines, and writing it yourself is how you find out whether you wanted leading or trailing edge.',
    caveats: ['immediate', 'leading', 'maxWait'],
  },
  {
    pkg: 'lodash.debounce',
    weekly: 12_000_000,
    api: 'setTimeout and a closure',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'Same five lines, unless you use maxWait, which is the one genuinely fiddly option.',
    caveats: ['maxWait', 'leading'],
  },
  {
    pkg: 'tmp',
    weekly: 20_000_000,
    api: 'fs.mkdtemp()',
    since: '5.10.0',
    confidence: 'partial',
    rationale: 'Core makes the directory; tmp also cleans up on exit, which is a process handler you write.',
    caveats: ['setGracefulCleanup', 'unsafeCleanup'],
  },
  {
    pkg: 'graceful-fs',
    weekly: 90_000_000,
    api: 'node:fs',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'It patches core fs to retry on EMFILE. Modern Node handles descriptor exhaustion far better, so on a supported version it is mostly inertia.',
  },
  {
    pkg: 'randombytes',
    weekly: 40_000_000,
    api: 'crypto.randomBytes()',
    since: '4.0.0',
    confidence: 'exact',
    rationale: 'The package is a browser shim for the core function it is named after.',
  },
  {
    pkg: 'hasha',
    weekly: 4_000_000,
    api: 'crypto.createHash()',
    since: '4.0.0',
    confidence: 'exact',
    rationale: 'Two core calls, and the streaming variant is a pipeline.',
  },
  {
    pkg: 'sha.js',
    weekly: 20_000_000,
    api: 'crypto.createHash()',
    since: '4.0.0',
    confidence: 'exact',
    rationale: 'A JavaScript reimplementation of a hash Node does natively and faster.',
  },
  {
    pkg: 'path-browserify',
    weekly: 15_000_000,
    api: 'node:path',
    since: '0.10.0',
    confidence: 'exact',
    rationale: 'A bundler shim for a core module; if it is reaching your Node build, something is misconfigured.',
  },
  {
    pkg: 'make-dir',
    weekly: 25_000_000,
    api: 'fs.mkdir(path, { recursive: true })',
    since: '10.12.0',
    confidence: 'exact',
    rationale: 'One option flag, same as mkdirp.',
  },
  {
    pkg: 'del',
    weekly: 8_000_000,
    api: 'fs.rm(path, { recursive: true, force: true })',
    since: '14.14.0',
    confidence: 'partial',
    rationale: 'Core deletes recursively; del also globs, which fs.globSync now does.',
    caveats: ['dryRun', 'onProgress'],
  },
  {
    pkg: 'strip-bom',
    weekly: 25_000_000,
    api: "text.replace(/^\\uFEFF/, '')",
    since: '4.0.0',
    confidence: 'exact',
    rationale: 'One regular expression, and reading with the utf8 encoding usually removes the need entirely.',
  },
  {
    pkg: 'slugify',
    weekly: 3_000_000,
    api: "String.normalize('NFKD') plus a replace",
    since: '4.0.0',
    confidence: 'partial',
    rationale: 'Unicode normalisation is native; transliterating non-Latin scripts is the part a package earns its place doing.',
    caveats: ['extend(', 'locale:'],
  },
  {
    pkg: 'p-map',
    weekly: 40_000_000,
    api: 'a Promise pool you write',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'There is no stdlib API for bounded concurrency; the replacement is about twenty lines you own.',
  },
  {
    pkg: 'p-retry',
    weekly: 15_000_000,
    api: 'a loop with backoff',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'No stdlib API; retry with exponential backoff is a dozen lines, and getting the jitter right is the interesting part.',
  },
  {
    pkg: 'node-cron',
    weekly: 1_000_000,
    api: 'setInterval, or a system scheduler',
    since: '18.0.0',
    confidence: 'partial',
    rationale: 'A fixed interval is one core call; real cron expressions, timezones and DST are why the package exists.',
    caveats: ['* * *', 'timezone', 'scheduled:'],
  },
];

/** @type {Map<string, Entry>} */
const BY_NAME = new Map(ENTRIES.map((entry) => [entry.pkg, entry]));

/** @param {string} pkg @returns {Entry|undefined} */
export function lookup(pkg) {
  return BY_NAME.get(pkg);
}

/** Total weekly downloads across a set of package names, ignoring unknowns. */
export function weeklyTotal(names) {
  let total = 0;
  for (const name of names) total += BY_NAME.get(name)?.weekly ?? 0;
  return total;
}
